### ISSUE TITLE
[  question of Installation  ]  :    HOW TO  "Attach the highlight.min.js file to that note"  ? 

### ISSUE THREAD

**Issue by ghost** [antoniotejada/Trilium-SyntaxHighlightWidget#3] opened 2022-07-02 13:39 UTC
[  question of Installation  ]  :    HOW TO  "Attach the highlight.min.js file to that note"  ? 

-------------------------------
1)   Create a code note of type JS Frontend with the contents of [SyntaxHighlightWidget.js](https://github.com/antoniotejada/Trilium-SyntaxHighlightWidget/blob/main/SyntaxHighlightWidget.js) and the label #widget

2)   Attach the [highlight.min.js](https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.5.1/highlight.min.js) file to that note

3)  To enable debug output, set the code note #debugLevel attribute to one of error, warn, info, log, debug (default is info)
--------------------------------------------------

**Comment by FluffMe** [comment] 2022-07-02 14:29
Hi,

1. Download the https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.5.1/highlight.min.js
2. Drag and drop it from your file manager onto the `SyntaxHighlightWidget.js` note. It will import and attach a child note with the contents of **highlight.min.js**

Alternatively, you can just create one yourself

1. Create a nested child note with the name **highlight.min.js** and type of **JS frontend**
2. Paste the full contents of https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.5.1/highlight.min.js into it.

Hope this helps.


**UPDATE:**
Looked further into it, the actual correct way is to:
1. Click a three dot menu on the right side of the **SyntaxHighlightWidget.js** note and select **Import files** option.
![image](https://user-images.githubusercontent.com/1780586/177005092-dd9a57a7-309b-4cb4-808f-ef7e5c2d5fcb.png)
2. Choose **highligh.min.js** from your drive and deselect every option. Then click **Import**.
![image](https://user-images.githubusercontent.com/1780586/177005129-6cbe1c2e-a5bf-46db-849d-cb33417caa18.png)

However, both options worked just fine for me.

**Comment by antoniotejada** [comment] 2022-07-03 00:46
@FluffMe thanks for taking the time to document the process, as you've found there are multiple ways of doing that, see https://github.com/antoniotejada/Trilium-SyntaxHighlightWidget/issues/1#issuecomment-1119695620

Closing.

**Closed as completed** 2022-07-03 00:46 UTC

**Comment by dreamyunight** [comment] 2024-09-25 11:40
@FluffMe When I imported the file as you described, it was wrong to import after removing all the checkboxes, just remove Safe import.
![jaslkdjfasdf](https://github.com/user-attachments/assets/ba4cd000-e0b5-4ca0-a449-485216235bbd)

**Comment by dreamyunight** [comment] 2024-09-25 11:43
> Hi,
> 
>     1. Download the https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.5.1/highlight.min.js
> 
>     2. Drag and drop it from your file manager onto the `SyntaxHighlightWidget.js` note. It will import and attach a child note with the contents of **highlight.min.js**
> 
> 
> Alternatively, you can just create one yourself
> 
>     1. Create a nested child note with the name **highlight.min.js** and type of **JS frontend**
> 
>     2. Paste the full contents of https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.5.1/highlight.min.js into it.
> 
> 
> Hope this helps.
> 
> **UPDATE:** Looked further into it, the actual correct way is to:
> 
>     1. Click a three dot menu on the right side of the **SyntaxHighlightWidget.js** note and select **Import files** option.
>        ![image](https://user-images.githubusercontent.com/1780586/177005092-dd9a57a7-309b-4cb4-808f-ef7e5c2d5fcb.png)
> 
>     2. Choose **highligh.min.js** from your drive and deselect every option. Then click **Import**.
>        ![image](https://user-images.githubusercontent.com/1780586/177005129-6cbe1c2e-a5bf-46db-849d-cb33417caa18.png)
> 
> 
> However, both options worked just fine for me.

When I followed your instructions to import the file, I encountered an error after unchecking all the checkboxes. It appears only need to uncheck the "Secure Import" option.
![jaslkdjfasdf](https://github.com/user-attachments/assets/3cd078d7-48b4-4278-97f1-bdf12d13a145)

**Comment by dreamyunight** [comment] 2024-09-25 11:44
@FluffMe When I followed your instructions to import the file, I encountered an error after unchecking all the checkboxes. It appears only need to uncheck the "Secure Import" option.
![jaslkdjfasdf](https://github.com/user-attachments/assets/d1a33fe4-758f-4a25-883c-fadf7297f40e)

**Comment by FluffMe** [comment] 2024-09-25 11:46
> @FluffMe When I followed your instructions to import the file, I encountered an error after unchecking all the checkboxes. It appears only need to uncheck the "Secure Import" option.
> ![jaslkdjfasdf](https://github.com/user-attachments/assets/d1a33fe4-758f-4a25-883c-fadf7297f40e)
> 

The issue is 2 year old. So no wonder the steps changed.

Glad you found a way to do it.
